### ISSUE TITLE
bug: `swapAndStartBridgeTokensViaHopL2ERC20` method ABI

### ISSUE THREAD

**Issue by bulgakovk** [lifinance/contracts#527]
Hey there! I've probably spotted a bug with the `swapAndStartBridgeTokensViaHopL2ERC20` method ABI in https://github.com/lifinance/contracts/blob/main/diamondABI/diamond.json. If you flat the struct types you'll get 
```
(bytes32,string,string,address,address,address,uint256,uint256,bool,bool),(address,address,address,address,uint256,bytes,bool)[],(uint256,uint256,uint256,uint256,uint256,address)
```

The function ID from that params will be `0x00d2aed6` what doesn't [match the explorers](https://polygonscan.com/tx/0x253dec76bd9ee781a84a0bf81be802a48154ece54bceade1a1cd709f4e33183b) (it says it should be `0xd40e64cc`). Looks like the ABI is missing 3 more types there (`address`, `uint256` and `uint256`). After adding them the function arguments look like 
```
(bytes32,string,string,address,address,address,uint256,uint256,bool,bool),(address,address,address,address,uint256,bytes,bool)[],(uint256,uint256,uint256,uint256,uint256,address,address,uint256,uint256)
```

and produce the proper method signature (`0xd40e64cc`)

**Comment by 0xDEnYO** [comment]
Hi @bulgakovk ,

sorry for the late response. 
Indeed the diamond ABI was outdated, thanks for spotting this issue. The ABI was produced before the HopFacetOptimized was updated and some parameters were added, thereby it became outdated.

We've improved our workflow now so that the diamondABI automatically gets generated with every new release of our lifi-contract-types package (which basically is generated with every new commit in our contracts repo).

You can find the latest diamondABI here:
https://github.com/lifinance/lifi-contract-types/blob/main/dist/diamond.json

If you should need any further assistance, please do not hesitate to contact us.
I will close this issue for now.
